import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    pokoje: {
      Agape: {
        1: {
          id: 1,
          title: 'Pokoj č.1 - Dvoulůžkový',
          tags: ['TV', 'Koupelna a WC'],
          roomType: 2,
          ceny: [990, 1190],
          fotky: [],
        },
        2: {
          id: 2,
          title: 'Pokoj č.2 - Dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [590, 890],
          fotky: [
            'pokoje/agape/2/P4230649.jpg',
            'pokoje/agape/2/P4230653.jpg',
            'pokoje/agape/2/P4230655.jpg',
          ],
        },
        3: {
          id: 3,
          title: 'Pokoj č.3 - Dvoulůžkový',
          tags: ['Rádio,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [690, 890],
          fotky: [
            'pokoje/agape/3/P4240850.jpg',
            'pokoje/agape/3/P4240851.jpg',
            'pokoje/agape/3/P4240854.jpg',
            'pokoje/agape/3/P4240856.jpg',
            'pokoje/agape/3/P4240857.jpg',
          ],
        },
        4: {
          id: 4,
          title: 'Pokoj č.4 - Jednolůžkový',
          tags: ['Radio,', 'Koupelna a WC'],
          roomType: 1,
          ceny: [590],
          fotky: [
            'pokoje/agape/4/IMG_5747.jpg',
            'pokoje/agape/4/IMG_5748.jpg',
            'pokoje/agape/4/IMG_5749.jpg',
          ],
        },
        5: {
          id: 5,
          title: 'Pokoj č.5 - Dvoulůžkový',
          tags: ['Radio,', 'Koupelna a WC'],
          roomType: 2,
          ceny: ['690', '990'],
          fotky: [
            'pokoje/agape/5/P4240800.jpg',
            'pokoje/agape/5/P4240802.jpg',
            'pokoje/agape/5/P4240803.jpg',
            'pokoje/agape/5/P4240804.jpg',
            'pokoje/agape/5/P4240805.jpg',
            'pokoje/agape/5/P4240806.jpg',
          ],
        },
        6: {
          id: 6,
          title: 'Pokoj č.6 - Dvoulůžkový',
          tags: ['Radio,', 'Koupelna a WC'],
          roomType: 2,
          ceny: ['690', '890'],
          fotky: [
            'pokoje/agape/6/AnyConv.com__P1010673_0.jpg',
            'pokoje/agape/6/AnyConv.com__P1010676.jpg',
          ],
        },
        7: {
          id: 7,
          title: 'Pokoj č.7 - Dvoulůžkový',
          tags: ['Radio,', 'Koupelna a WC'],
          roomType: 2,
          ceny: ['690', '890'],
          fotky: [
            'pokoje/agape/7/P1010673_0.jpg',
            'pokoje/agape/7/P4240812.jpg',
          ],
        },
        8: {
          id: 8,
          title: 'Pokoj č.8 - Dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: ['690', '990'],
          fotky: [
            'pokoje/agape/8/P4230668.jpg',
            'pokoje/agape/8/P4230669.jpg',
            'pokoje/agape/8/P4230671.jpg',
          ],
        },
        9: {
          id: 9,
          title: 'Pokoj č.9 - Čtyřlůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 4,
          ceny: ['1590', '1890'],
          fotky: [
            'pokoje/agape/9/P4240832.jpg',
            'pokoje/agape/9/P4240834.jpg',
            'pokoje/agape/9/P4240836.jpg',
            'pokoje/agape/9/P4240837.jpg',
            'pokoje/agape/9/P4240838.jpg',
            'pokoje/agape/9/P4240839.jpg',
          ],
        },
        10: {
          id: 10,
          title: 'Pokoj č.10 - Dvoulůžkový',
          tags: ['Balkón,', 'Radio,', 'Koupelna a WC'],
          roomType: 2,
          ceny: ['1090', '1790'],
          fotky: [
            'pokoje/agape/10/P4240841.jpg',
            'pokoje/agape/10/P4240842.jpg',
            'pokoje/agape/10/P4240843.jpg',
            'pokoje/agape/10/P4240844.jpg',
            'pokoje/agape/10/P4240845.jpg',
            'pokoje/agape/10/P4240848.jpg',
          ],
        },
        11: {
          id: 11,
          title: 'Pokoj č. 11 apartmán - Dvoulůžkový',
          tags: [
            'TV,',
            'Radio,',
            'Koupelna a WC,',
            'Lednice',
            'Pro 2 osoby + přístýlka 1790 Kč / noc',
            'Pro 2 osoby + přístýlka pro dva 1990 Kč / noc',
          ],
          roomType: 2,
          ceny: ['1290', '1290'],
          fotky: [
            'pokoje/agape/11/1.jpg',
            'pokoje/agape/11/2.jpg',
            'pokoje/agape/11/3.jpg',
            'pokoje/agape/11/4.jpg',
            'pokoje/agape/11/5.jpg',
          ],
        },
        12: {
          id: 12,
          title: 'Pokoj č. 12 - třílůžkový',
          tags: ['TV,', 'Radio,', 'Sdílená koupelna a WC'],
          roomType: 3,
          ceny: ['690', '980', '1390'],
          fotky: [
            'pokoje/agape/12/P4240825.jpg',
            'pokoje/agape/12/P4240828.jpg',
            'pokoje/agape/12/P4240829.jpg',
          ],
        },
        13: {
          id: 13,
          title: 'Pokoj č. 13 - Jednolůžkový',
          tags: ['Radio,', 'Sdílená koupelna a WC'],
          roomType: 1,
          ceny: ['690'],
          fotky: [
            'pokoje/agape/13/P4240819.jpg',
            'pokoje/agape/13/P4240820.jpg',
            'pokoje/agape/13/P4240821.jpg',
          ],
        },
        14: {
          id: 14,
          title: 'Pokoj č.14 - Jednolůžkový',
          tags: ['Sdílená koupelna a WC'],
          roomType: 1,
          ceny: ['590'],
          fotky: [],
        },
      },
      Jecminek: {
        1: {
          id: 1,
          title: 'Pokoj č.1 - dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [690, 990],
          fotky: [
            'pokoje/jecminek/1/P1211976.jpg',
            'pokoje/jecminek/1/P1211977.jpg',
            'pokoje/jecminek/1/P1212.jpg',
            'pokoje/jecminek/1/P1211980.jpg',
            'pokoje/jecminek/1/P1211981.jpg',
          ],
        },
        2: {
          id: 2,
          title: 'Pokoj č.2 - dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [690, 990],
          fotky: [
            'pokoje/jecminek/2/IMG_0403_0.png',
            'pokoje/jecminek/2/IMG_0404_0.png',
            'pokoje/jecminek/2/IMG_0405_0.png',
            'pokoje/jecminek/2/IMG_0406_1.png',
          ],
        },
        3: {
          id: 3,
          title: 'Pokoj č.3 - dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [690, 990],
          fotky: [
            'pokoje/jecminek/3/IMG_0408.png',
            'pokoje/jecminek/3/IMG_0409.png',
            'pokoje/jecminek/3/IMG_0410.png',
            'pokoje/jecminek/3/IMG_0411.png',
          ],
        },
        4: {
          id: 4,
          title: 'Pokoj č.4 - dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [690, 990],
          fotky: [
            'pokoje/jecminek/4/IMG_3306.jpg',
            'pokoje/jecminek/4/IMG_3307.jpg',
            'pokoje/jecminek/4/IMG_3311.jpg',
            'pokoje/jecminek/4/IMG_3314.jpg',
            'pokoje/jecminek/4/IMG_3315.jpg ',
          ],
        },
        5: {
          id: 5,
          title: 'Pokoj č.5 - dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [690, 990],
          fotky: [
            'pokoje/jecminek/5/IMG_0418.png',
            'pokoje/jecminek/5/IMG_0421.png',
            'pokoje/jecminek/5/IMG_0422.png',
          ],
        },
      },
      Jecminek2: {
        1: {
          id: 1,
          title: 'Pokoj č.1 - Dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [690, 990],
          fotky: [
            'pokoje/jecminek2/1/IMG_3175.jpg',
            'pokoje/jecminek2/1/IMG_3176.jpg',
            'pokoje/jecminek2/1/IMG_3180.jpg',
            'pokoje/jecminek2/1/IMG_3182.jpg',
            'pokoje/jecminek2/1/IMG_3183.jpg',
            'pokoje/jecminek2/1/IMG_3184.jpg',
          ],
        },
        2: {
          id: 2,
          title: 'Pokoj č.2 - Jednolůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 1,
          ceny: [690],
          fotky: [
            'pokoje/jecminek2/2/P5132082.jpg',
            'pokoje/jecminek2/2/P5132083.jpg',
            'pokoje/jecminek2/2/P5132084.jpg',
          ],
        },
        3: {
          id: 3,
          title: 'Pokoj č.3 - Dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [690, 990],
          fotky: [
            'pokoje/jecminek2/3/IMG_3549.jpg',
            'pokoje/jecminek2/3/IMG_3550.jpg',
            'pokoje/jecminek2/3/IMG_3553.jpg',
            'pokoje/jecminek2/3/IMG_3554.jpg',
            'pokoje/jecminek2/3/IMG_3555.jpg',
            'pokoje/jecminek2/3/IMG_3557.jpg',
            'pokoje/jecminek2/3/IMG_3558.jpg',
            'pokoje/jecminek2/3/IMG_3559.jpg',
          ],
        },
        4: {
          id: 4,
          title: 'Pokoj č.4 - Jednolůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 1,
          ceny: [690],
          fotky: [
            'pokoje/jecminek2/4/IMG_3412.jpg',
            'pokoje/jecminek2/4/IMG_3414.jpg',
            'pokoje/jecminek2/4/IMG_3415.jpg',
            'pokoje/jecminek2/4/IMG_3416.jpg',
            'pokoje/jecminek2/4/IMG_3419.jpg',
            'pokoje/jecminek2/4/IMG_3422.jpg',
          ],
        },
        5: {
          id: 5,
          title: 'Pokoj č.5 - Dvoulůžkový',
          tags: ['TV,', 'Koupelna a WC'],
          roomType: 2,
          ceny: [690, 990],
          fotky: [
            'pokoje/jecminek2/5/IMG_3424.jpg',
            'pokoje/jecminek2/5/IMG_3425.jpg',
            'pokoje/jecminek2/5/IMG_3431.jpg',
            'pokoje/jecminek2/5/IMG_3430.jpg',
            'pokoje/jecminek2/5/IMG_3432.jpg',
          ],
        },
        6: {
          id: 6,
          title: 'Pokoj č.6 - Jednolůžkový',
          tags: ['Umyvadlo,', 'Sdílená koupelna a WC'],
          roomType: 1,
          ceny: [450],
          fotky: [
            'pokoje/jecminek2/6/IMG_0380.png',
            'pokoje/jecminek2/6/IMG_0381.jpg',
          ],
        },
        7: {
          id: 7,
          title: 'Pokoj č.7 - Dvoulůžkový',
          tags: ['Umyvadlo', 'Sdílená koupelna a WC'],
          roomType: 2,
          ceny: [590, 790],
          fotky: [
            'pokoje/jecminek2/7/IMG_0383.png',
            'pokoje/jecminek2/7/IMG_0385.png',
          ],
        },
        8: {
          id: 8,
          title: 'Pokoj č.8 - Dvoulůžkový',
          tags: ['Umyvadlo', 'Sdílená koupelna a WC'],
          roomType: 2,
          ceny: [590, 790],
          fotky: [
            'pokoje/jecminek2/8/IMG_0389.png',
            'pokoje/jecminek2/8/IMG_0390.png',
          ],
        },
        9: {
          id: 9,
          title: 'Pokoj č.9 - Dvoulůžkový',
          tags: ['Sdílená koupelna a WC', 'Balkón'],
          roomType: 2,
          ceny: [590, 790],
          fotky: [
            'pokoje/jecminek2/9/jecminek9_0.jpg',
            'pokoje/jecminek2/9/jecminek9-1.png',
            'pokoje/jecminek2/9/jecminek9-2.jpg',
          ],
        },
      },
    },
    info: {
      oteviraciDoba: '10:00 - 18:00',
      telefon: ['734 727 373', '603 194 233'],
      email: 'rezervace@penzionyluhacovice.cz',
    },
  },
  mutations: {},
  actions: {},
  modules: {},
})
